# Generated by Django 4.0 on 2021-12-12 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('id_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_recipient', to='auth.user')),
                ('id_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_sender', to='auth.user')),
            ],
        ),
    ]
